# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 14 May 2013 03:40:13 +0000
*               @ALL          0
*               @user         8
start	@user	1
start	@editor	2
contacts:*	@user	1
contacts:*	@contacts	8
projects:start	@user	1
projects:start	@editor	2
public:*	@ALL	1
resources:restricted	@user	0
resources:restricted	@editor	2
