<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Mon, 13 May 2013 22:08:14 -0700
 */

$conf['title'] = 'Another Activist Wiki';
$conf['template'] = 'vector';
$conf['license'] = '0';
$conf['breadcrumbs'] = 5;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['subscribers'] = 1;
$conf['plugin']['include']['usernamespace'] = 'wiki:user';
$conf['plugin']['database2']['customviews'] = 1;
$conf['plugin']['database2']['enablepages'] = 'projects:*
contacts:*
help:plugins';
$conf['plugin']['blog']['excluded_pages'] = '!^blog:(start|\\d{4}(:\\d{2})?)$!';
$conf['tpl']['vector']['vector_qrcodebox'] = 0;
$conf['tpl']['vector']['vector_copyright_translate'] = 0;
$conf['tpl']['vector']['vector_donate'] = 0;
$conf['tpl']['vector']['vector_cite_author'] = 'Various contributors';

// end auto-generated content
